services:
  app:
    build:
      context: .
      target: runner
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - movie-web

  migrate:
    build:
      context: .
      target: builder
    env_file:
      - .env
    command: yarn prisma migrate deploy
    networks:
      - movie-web

networks:
  movie-web:
    external: true